name: Ejemplo de Flujo de Trabajo

on:
  push:
    branches:
      - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "¡Hola, mundo!"

  despedirse:
    runs-on: ubuntu-latest
    needs: saludar
    steps:
      - name: Despedirse
        run: echo "¡Adiós, mundo!"
